# Generated by Django 2.0 on 2023-07-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('sequence', models.IntegerField(verbose_name='Sequence')),
                ('note', models.TextField(max_length=100, verbose_name='Note')),
                ('quality', models.TextField(max_length=100, verbose_name='Quality')),
                ('product', models.TextField(max_length=100, verbose_name='Product')),
                ('price', models.IntegerField(max_length=100, verbose_name='Price')),
                ('total', models.IntegerField(max_length=100, verbose_name='Total')),
                ('reason', models.TextField(max_length=100, verbose_name='Reason')),
                ('status', models.CharField(default='draft', max_length=10, verbose_name='Status')),
                ('attachment', models.ImageField(blank=True, default=None, upload_to='', verbose_name='Image')),
            ],
            options={
                'permissions': (('view_expensemodel', 'Can view expense model'),),
            },
        ),
    ]
