# Generated by Django 2.0 on 2023-07-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_attendances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancemodel',
            name='employee',
        ),
    ]
